var cWidth = window.innerWidth - 20;
var cHeight = 550;
var dragIndex;
var dragging;
var mouseOver;
var mouseX;
var mouseY;
var dragHoldX;
var dragHoldY;
var circles = [];
var lines = [];
var linesSelectedCircle = [];
var minRadiusCircle = 2;
var lineWidth = 1;
var i = 0;
var minConnectValue = 3;